package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_docker//container:container.bzl", "container_image")
load("@package_bundle//file:packages.bzl", "packages")

container_image(
    name = "master",
    base = "@nodejs//image:image.tar",
    debs = [
        packages["libssl1.0.2"],
        packages["openssh-client"],
        packages["dash"],
        packages["libtinfo5"],
        packages["debianutils"],
        packages["bash"],
        packages["libpcre3"],
        packages["libattr1"],
        packages["libacl1"],
        packages["libbz2-1.0"],
        packages["liblzma5"],
        packages["multiarch-support"],
        packages["libselinux1"],
        packages["zlib1g"],
        packages["tar"],
        packages["libcom-err2"],
        packages["libgnutls30"],
        packages["libgmp10"],
        packages["libnettle6"],
        packages["libhogweed4"],
        packages["libidn11"],
        packages["libffi6"],
        packages["libp11-kit0"],
        packages["libtasn1-6"],
        packages["libkeyutils1"],
        packages["libkrb5support0"],
        packages["libgssapi-krb5-2"],
        packages["libk5crypto3"],
        packages["libkrb5-3"],
        packages["libdb5.3"],
        packages["libsasl2-modules-db"],
        packages["libsasl2-2"],
        packages["libldap-common"],
        packages["libldap-2.4-2"],
        packages["libunistring0"],
        packages["libpsl5"],
        packages["librtmp1"],
        packages["libgpg-error0"],
        packages["libgcrypt20"],
        packages["libssh2-1"],
        packages["perl-base"],
        packages["perl-modules-5.24"],
        packages["libgdbm3"],
        packages["libperl5.24"],
        packages["perl"],
        packages["liberror-perl"],
        packages["dpkg"],
        packages["git-man"],
        packages["libcurl3-gnutls"],
        packages["libexpat1"],
        packages["libnghttp2-14"],
        packages["libidn2-0"],
        packages["libcurl3"],
        packages["curl"],
        packages["git"],
        packages["coreutils"],
        packages["gzip"]
    ],
    env = {"PATH": "$PATH:/nodejs/bin/"},
    repository = "drydock/distrobase"
)
